<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\AttributeDefinition;
use Illuminate\Database\Seeder;

class AttributeDefinitionsSeeder extends Seeder
{
    public function run(): void
    {
        $attributes = [

            // ── SCHEMA: eduperson ─────────────────────────────────────────────
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonPrincipalName',
                'full_name'   => 'Principal Name',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonPrincipalName',
                'description' => 'A scoped identifier for a person',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonScopedAffiliation',
                'full_name'   => 'Scoped Affiliation',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.9',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonScopedAffiliation',
                'description' => 'Specifies the persons affiliation within a scope',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonAffiliation',
                'full_name'   => 'Affiliation',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.1',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonAffiliation',
                'description' => 'Specifies the persons relationship to the institution',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonPrimaryAffiliation',
                'full_name'   => 'Primary Affiliation',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.5',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation',
                'description' => 'Specifies the primary relationship to the institution',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonEntitlement',
                'full_name'   => 'Entitlement',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.7',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonEntitlement',
                'description' => 'URI indicating a right to specific resources',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonAssurance',
                'full_name'   => 'Assurance Level',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.11',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonAssurance',
                'description' => 'URI indicating identity assurance profile',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonUniqueId',
                'full_name'   => 'Unique ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.13',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonUniqueId',
                'description' => 'Opaque unique identifier for a person',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonOrcid',
                'full_name'   => 'ORCID iD',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.16',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonOrcid',
                'description' => 'ORCID researcher identifier',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonNickname',
                'full_name'   => 'Nickname',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.2',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonNickname',
                'description' => 'Persons nickname or informal name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonPrimaryOrgUnitDN',
                'full_name'   => 'Primary Org Unit DN',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.8',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonPrimaryOrgUnitDN',
                'description' => 'DN of the primary organizational unit',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonOrgDN',
                'full_name'   => 'Org DN',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.3',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonOrgDN',
                'description' => 'DN of the home organization',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonOrgUnitDN',
                'full_name'   => 'Org Unit DN',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.4',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonOrgUnitDN',
                'description' => 'DN of the organizational unit',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'eduperson',
                'name'        => 'eduPersonTargetedID',
                'full_name'   => 'Targeted ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:eduPersonTargetedID',
                'description' => 'Opaque targeted identifier (deprecated, use eduPersonUniqueId)',
                'is_required' => false,
                'is_active'   => true,
            ],

            // ── SCHEMA: ldap ──────────────────────────────────────────────────
            [
                'schema'      => 'ldap',
                'name'        => 'uid',
                'full_name'   => 'User Identifier',
                'saml2_oid'   => 'urn:oid:0.9.2342.19200300.100.1.1',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:uid',
                'description' => 'User identifier',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'cn',
                'full_name'   => 'Common Name',
                'saml2_oid'   => 'urn:oid:2.5.4.3',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:cn',
                'description' => 'Common name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'sn',
                'full_name'   => 'Surname',
                'saml2_oid'   => 'urn:oid:2.5.4.4',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:sn',
                'description' => 'Surname',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'givenName',
                'full_name'   => 'Given Name',
                'saml2_oid'   => 'urn:oid:2.5.4.42',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:givenName',
                'description' => 'Given name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'displayName',
                'full_name'   => 'Display Name',
                'saml2_oid'   => 'urn:oid:2.16.840.1.113730.3.1.241',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:displayName',
                'description' => 'Preferred name for display',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'mail',
                'full_name'   => 'Email Address',
                'saml2_oid'   => 'urn:oid:0.9.2342.19200300.100.1.3',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:mail',
                'description' => 'Email address',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'o',
                'full_name'   => 'Organisation',
                'saml2_oid'   => 'urn:oid:2.5.4.10',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:o',
                'description' => 'Organization name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'title',
                'full_name'   => 'Title',
                'saml2_oid'   => 'urn:oid:2.5.4.12',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:title',
                'description' => 'Job title',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'telephoneNumber',
                'full_name'   => 'Telephone Number',
                'saml2_oid'   => 'urn:oid:2.5.4.20',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:telephoneNumber',
                'description' => 'Telephone number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'facsimileTelephoneNumber',
                'full_name'   => 'Fax Number',
                'saml2_oid'   => 'urn:oid:2.5.4.23',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:facsimileTelephoneNumber',
                'description' => 'Facsimile telephone number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'street',
                'full_name'   => 'Street Address',
                'saml2_oid'   => 'urn:oid:2.5.4.9',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:street',
                'description' => 'Street address',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'l',
                'full_name'   => 'Locality',
                'saml2_oid'   => 'urn:oid:2.5.4.7',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:l',
                'description' => 'Locality name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'st',
                'full_name'   => 'State',
                'saml2_oid'   => 'urn:oid:2.5.4.8',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:st',
                'description' => 'State or province name',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'postalCode',
                'full_name'   => 'Postal Code',
                'saml2_oid'   => 'urn:oid:2.5.4.17',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:postalCode',
                'description' => 'Postal code',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'postOfficeBox',
                'full_name'   => 'Post Office Box',
                'saml2_oid'   => 'urn:oid:2.5.4.18',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:postOfficeBox',
                'description' => 'Post office box number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'description',
                'full_name'   => 'Description',
                'saml2_oid'   => 'urn:oid:2.5.4.13',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:description',
                'description' => 'Description of the entry',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'labeledURI',
                'full_name'   => 'Labeled URI',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.250.1.57',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:labeledURI',
                'description' => 'Uniform resource identifier with label',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'preferredLanguage',
                'full_name'   => 'Preferred Language',
                'saml2_oid'   => 'urn:oid:2.16.840.1.113730.3.1.39',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:preferredLanguage',
                'description' => 'Preferred written or spoken language',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'employeeNumber',
                'full_name'   => 'Employee Number',
                'saml2_oid'   => 'urn:oid:2.16.840.1.113730.3.1.3',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:employeeNumber',
                'description' => 'Employee number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'employeeType',
                'full_name'   => 'Employee Type',
                'saml2_oid'   => 'urn:oid:2.16.840.1.113730.3.1.4',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:employeeType',
                'description' => 'Type of employee',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'businessCategory',
                'full_name'   => 'Business Category',
                'saml2_oid'   => 'urn:oid:2.5.4.15',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:businessCategory',
                'description' => 'Business category',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'departmentNumber',
                'full_name'   => 'Department Number',
                'saml2_oid'   => 'urn:oid:2.16.840.1.113730.3.1.2',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:departmentNumber',
                'description' => 'Department number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'roomNumber',
                'full_name'   => 'Room Number',
                'saml2_oid'   => 'urn:oid:0.9.2342.19200300.100.1.6',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:roomNumber',
                'description' => 'Room number',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'manager',
                'full_name'   => 'Manager',
                'saml2_oid'   => 'urn:oid:0.9.2342.19200300.100.1.10',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:manager',
                'description' => 'DN of the managers entry',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'secretary',
                'full_name'   => 'Secretary',
                'saml2_oid'   => 'urn:oid:0.9.2342.19200300.100.1.21',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:secretary',
                'description' => 'DN of the secretarys entry',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'ldap',
                'name'        => 'userPassword',
                'full_name'   => 'User Password',
                'saml2_oid'   => 'urn:oid:2.5.4.35',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:userPassword',
                'description' => 'Password (release with extreme caution)',
                'is_required' => false,
                'is_active'   => false,
            ],

            // ── SCHEMA: schac ─────────────────────────────────────────────────
            [
                'schema'      => 'schac',
                'name'        => 'schacHomeOrganization',
                'full_name'   => 'Home Organisation',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.9',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacHomeOrganization',
                'description' => 'Domain name of the home organization',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacHomeOrganizationType',
                'full_name'   => 'Home Organisation Type',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.10',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacHomeOrganizationType',
                'description' => 'Type of the home organization',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacPersonalUniqueCode',
                'full_name'   => 'Personal Unique Code',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.14',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacPersonalUniqueCode',
                'description' => 'Unique code for the person',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacPersonalUniqueID',
                'full_name'   => 'Personal Unique ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.15',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacPersonalUniqueID',
                'description' => 'Unique identifier for the person',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacMotherTongue',
                'full_name'   => 'Mother Tongue',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.1',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacMotherTongue',
                'description' => 'Persons mother tongue language code',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacGender',
                'full_name'   => 'Gender',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.2',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacGender',
                'description' => 'Persons gender',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacDateOfBirth',
                'full_name'   => 'Date of Birth',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.3',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacDateOfBirth',
                'description' => 'Date of birth (YYYYMMDD)',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacPlaceOfBirth',
                'full_name'   => 'Place of Birth',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.4',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacPlaceOfBirth',
                'description' => 'Place of birth',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacCountryOfCitizenship',
                'full_name'   => 'Country of Citizenship',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.5',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacCountryOfCitizenship',
                'description' => 'Country of citizenship (ISO 3166)',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacCountryOfResidence',
                'full_name'   => 'Country of Residence',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.11',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacCountryOfResidence',
                'description' => 'Country of residence (ISO 3166)',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacSn1',
                'full_name'   => 'First Surname',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.6',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacSn1',
                'description' => 'First surname',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacSn2',
                'full_name'   => 'Second Surname',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.7',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacSn2',
                'description' => 'Second surname',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacPersonalTitle',
                'full_name'   => 'Personal Title',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.8',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacPersonalTitle',
                'description' => 'Personal title (Dr, Prof, etc.)',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacPersonalPosition',
                'full_name'   => 'Personal Position',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.12',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacPersonalPosition',
                'description' => 'Position within the organization',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacUserPresenceID',
                'full_name'   => 'User Presence ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.13',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacUserPresenceID',
                'description' => 'Identifier for presence systems (Jabber, Skype etc.)',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'schac',
                'name'        => 'schacExpiryDate',
                'full_name'   => 'Expiry Date',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.1.2.17',
                'saml1_urn'   => 'urn:mace:terena.org:attribute-def:schacExpiryDate',
                'description' => 'Date when the account expires',
                'is_required' => false,
                'is_active'   => true,
            ],

            // ── SCHEMA: voperson ──────────────────────────────────────────────
            [
                'schema'      => 'voperson',
                'name'        => 'voPersonID',
                'full_name'   => 'VO Person ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.4.1.6',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:voPersonID',
                'description' => 'Unique identifier within a Virtual Organisation',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'voperson',
                'name'        => 'voPersonSoRID',
                'full_name'   => 'VO Person SoR ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.4.1.7',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:voPersonSoRID',
                'description' => 'System of Record identifier for VO person',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'voperson',
                'name'        => 'voPersonAffiliation',
                'full_name'   => 'VO Person Affiliation',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.4.1.2',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:voPersonAffiliation',
                'description' => 'Affiliation within a Virtual Organisation',
                'is_required' => false,
                'is_active'   => true,
            ],
            [
                'schema'      => 'voperson',
                'name'        => 'voPersonExternalID',
                'full_name'   => 'VO Person External ID',
                'saml2_oid'   => 'urn:oid:1.3.6.1.4.1.25178.4.1.3',
                'saml1_urn'   => 'urn:mace:dir:attribute-def:voPersonExternalID',
                'description' => 'External identifier for VO person',
                'is_required' => false,
                'is_active'   => true,
            ],
        ];

        foreach ($attributes as $data) {
            $existing = AttributeDefinition::where('name', $data['name'])->first();

            if ($existing) {
                $existing->update(['schema' => $data['schema']]);
            } else {
                AttributeDefinition::create($data);
            }
        }
    }
}
