<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\NotificationType;
use Illuminate\Database\Seeder;

class NotificationTypesSeeder extends Seeder
{
    private const TYPES = [
        [
            'id'                         => 'entity_pending_approval',
            'label'                      => 'Entity pending approval',
            'description'                => 'Fired when an entity is submitted to a federation and is awaiting approval.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => true,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'entity_approved',
            'label'                      => 'Entity approved',
            'description'                => 'Fired when a federation manager approves an entity join request.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'entity_rejected',
            'label'                      => 'Entity rejected',
            'description'                => 'Fired when a federation manager rejects an entity join request.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'entity_suspended',
            'label'                      => 'Entity suspended',
            'description'                => 'Fired when an entity is suspended.',
            'notify_submitter'           => true,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => true,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'certificate_expiring',
            'label'                      => 'Certificate expiring soon',
            'description'                => 'Fired when an entity certificate is approaching its expiry date.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'certificate_expired',
            'label'                      => 'Certificate expired',
            'description'                => 'Fired when an entity certificate has already expired.',
            'notify_submitter'           => true,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'user_registered',
            'label'                      => 'New user registered',
            'description'                => 'Fired when a new user account is created via invitation or SSO.',
            'notify_submitter'           => false,
            'notify_federation_managers' => false,
            'notify_admins'              => true,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'invitation_request_created',
            'label'                      => 'Invitation request created',
            'description'                => 'Fired when a new invitation request is submitted for review.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => true,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'invitation_request_approved',
            'label'                      => 'Invitation request approved',
            'description'                => 'Fired when an invitation request is approved and the invitation is sent.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'invitation_request_rejected',
            'label'                      => 'Invitation request rejected',
            'description'                => 'Fired when an invitation request is rejected.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'metadata_generated',
            'label'                      => 'Metadata generated',
            'description'                => 'Fired when federation metadata is successfully regenerated.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_deactivated',
            'label'                      => 'Federation deactivated',
            'description'                => 'Fired when a federation is deactivated.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => true,
            'notify_entity_technical'    => true,
            'notify_entity_admin'        => true,
            'default_via_ui'             => true,
            'notify_email'               => true,
        ],
        [
            'id'                         => 'federation_entity_invitation',
            'label'                      => 'Federation invitation received',
            'description'                => 'A federation has invited your entity to join.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_entity_invitation_accepted',
            'label'                      => 'Federation invitation accepted',
            'description'                => 'An entity has accepted your federation invitation.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_entity_invitation_rejected',
            'label'                      => 'Federation invitation declined',
            'description'                => 'An entity has declined your federation invitation.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'validator_failed',
            'label'                      => 'Mandatory validator failed',
            'description'                => 'Fired when a mandatory external validator fails during entity validation.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_reactivated',
            'label'                      => 'Federation reactivated',
            'description'                => 'Fired when an inactive federation is set back to active.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_deleted',
            'label'                      => 'Federation deleted',
            'description'                => 'Fired when a federation is soft-deleted.',
            'notify_submitter'           => false,
            'notify_federation_managers' => true,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'federation_manager_assigned',
            'label'                      => 'Federation manager assigned',
            'description'                => 'Fired when a user is assigned as a federation manager.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'user_role_changed',
            'label'                      => 'User role changed',
            'description'                => 'Fired when an administrator changes a user\'s role.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'user_suspended',
            'label'                      => 'User account suspended',
            'description'                => 'Fired when an administrator suspends a user account.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
        [
            'id'                         => 'user_reinstated',
            'label'                      => 'User account reinstated',
            'description'                => 'Fired when an administrator reinstates a suspended user account.',
            'notify_submitter'           => true,
            'notify_federation_managers' => false,
            'notify_admins'              => false,
            'notify_entity_technical'    => false,
            'notify_entity_admin'        => false,
            'default_via_ui'             => true,
            'notify_email'               => false,
        ],
    ];

    public function run(): void
    {
        foreach (self::TYPES as $type) {
            NotificationType::firstOrCreate(
                ['id' => $type['id']],
                array_merge($type, ['mail_template_id' => null])
            );
        }
    }
}
