<?php

declare(strict_types=1);

namespace App\Services\Metadata\Rules\Certificate;

use App\Models\Entity;
use App\Services\Metadata\Rules\Contracts\MetadataRule;
use App\Services\Metadata\Rules\Contracts\RuleResult;

final class C04_NotDebianWeak implements MetadataRule
{
    public function id(): string          { return 'C04'; }
    public function name(): string        { return 'Certificate is not a Debian weak key (CVE-2008-0166)'; }
    public function group(): string       { return 'certificate'; }
    public function appliesTo(): array    { return ['idp', 'sp']; }
    public function defaultSeverity(): string { return 'error'; }
    public function specUrl(): string     { return 'https://wiki.debian.org/SSLkeys'; }

    public function description(): string
    {
        return 'No certificate may be generated by the vulnerable Debian OpenSSL PRNG (CVE-2008-0166). These keys are publicly known and must be replaced immediately.';
    }

    public function evaluate(Entity $entity): RuleResult
    {
        if ($entity->certificates->isEmpty()) {
            return RuleResult::notApplicable($this->id());
        }

        $weak = $entity->certificates->filter(fn($cert) => (bool) $cert->debian_weak);

        if ($weak->isEmpty()) {
            return RuleResult::pass($this->id(), 'No Debian weak keys detected.');
        }

        $detail = $weak->map(fn($cert) => "Fingerprint: {$cert->fingerprint}")->implode('; ');

        return RuleResult::fail(
            $this->id(),
            'Debian weak key detected (CVE-2008-0166) — this certificate must be replaced immediately.',
            $detail,
        );
    }
}
